#任务名
name: autoDeploy
#触发条件
on:
    push:   
        branches: [ master ]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@master
              with:
                  java-version: 8
                  distribution: "adopt"
                  cache: maven
            - run: mvn clean -DfinalName=jeecg-boot package --file pom.xml
            - name: copy file
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.KEY }}
                  source: "target/jeecg-boot.jar"
                  rm: true
                  target: "/home/yygy/jeecg-boot"
            - name: Deploy
              uses: appleboy/ssh-action@masterauth
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  command_timeout: 20s
                  script: | 
                    cd /home/yygy/jeecg-boot/target
                    #ps -ef | grep jeecg-boot.jar | grep -v grep | awk '{print $2}' | xargs kill -9 
                    #nohup java -jar jeecg-boot.jar --spring.profiles.active=formal > nohup.out &
                    pwd
                    exit
